### ISSUE TITLE
Redis limiter on version 3.0.2 TypeError: Invalid argument type TypeError: result is not iterable

### ISSUE THREAD

**Issue by stx** [animir/node-rate-limiter-flexible#228] opened 2023-10-21 01:55 UTC
Just upgraded from 2.4.2 and not able to get this to work anymore.

```
TypeError: Invalid argument type
TypeError: result is not iterable
    at RateLimiterRedis._getRateLimiterRes (/usr/src/app/node_modules/rate-limiter-flexible/lib/RateLimiterRedis.js:64:32)
    at RateLimiterRedis._afterConsume (/usr/src/app/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:51:22)
    at /usr/src/app/node_modules/rate-limiter-flexible/lib/RateLimiterStoreAbstract.js:205:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by animir** [comment] 2023-10-21 10:37
@stx Hi, thanks for reporting this. What package and version do you use as Redis client?

**Comment by animir** [comment] 2023-10-24 17:59
@stx I guess, you solved the issue.
I am closing this one. Feel free to re-open if needed.

**Closed by animir** 2023-10-24 17:59 UTC
Labels: question

**Comment by Steffen911** [comment] 2025-01-30 15:49
Hey @animir ,
I think we observe the same error on 5.0.3 using Redis as a backend. I have all details in https://github.com/redis/ioredis/issues/1931, but perhaps there is a patch that would work on the node-rate-limiter-flexible level.

**Comment by animir** [comment] 2025-01-30 16:36
@Steffen911 Hi, thanks for reporting this.
Is the error reproducible?

**Comment by Steffen911** [comment] 2025-01-30 17:11
@animir Unfortunately, it is not. We observed it ~4x in the past two weeks even though there are thousands of rate limiting operations per minute. I.e. it happens very rarely.

**Comment by animir** [comment] 2025-01-30 19:14
@Steffen911 IHopefully, disabling autoPipline will fix the issue.
If so, that would indicate that ioredis has bugs in auto pipelining mode.

**Comment by Steffen911** [comment] 2025-02-01 10:19
Yeah, it looks like disabling the auto pipelining helped here. Thank you for the confirmation. In that case, I'll make sure to follow-up with https://github.com/redis/ioredis/issues/1931.
